# Generated by Django 3.2.8 on 2021-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0009_routergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
